name: Build (stable)

on: push

strategy:
    matrix:
        os: [windows-2019, ubuntu-16.04]
        include:
            - os: windows-2019
              script_name: .\build.cmd
            - os: ubuntu-16.04
              script_name: ./build.sh

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
            - os: windows-latest
              script_name: echo wip
            - os: ubuntu-latest
              script_name: sudo apt-get install mercurial
            - os: macos-latest
              script_name: brew install mercurial

    steps:
      - name: Install Mercurial
        run: ${{ matrix.script_name }}
