name: Build (stable)

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dot cli (2.1.0)
        run: npm i @dothq/build@2.1.0 -g
  
      - name: Downloading source code
        run: dot get dot

      - name: Check source
        run: ls
