name: Build (stable)

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
            - os: windows-latest
              script_name: echo wip
            - os: ubuntu-latest
              script_name: sudo apt-get install mercurial
            - os: macos-latest
              script_name: brew install mercurial

    steps:
      - name: Install Mercurial
        run: ${{ matrix.script_name }}

      - name: Setup development environment
        run: ls && python3 ./bootstrap.py

      - name: Build Dot Browser
        run: cd dot && ./mach build
