name: Sync

on:
  schedule:
    - cron: '*/1 * * * *' # every minute
  workflow_dispatch: # manually run sync
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync repo
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/dothq/ffr"
          source_branch: "release"
          destination_branch: "ff-gha"
          github_token: ${{ secrets.ROBOT_TOKEN }}
