name: Update submodules

on: [push, workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          cd desktop && git fetch && git checkout $(git log --branches -1 --pretty=format:"%H") && cd ..
          cd android && git fetch && git checkout $(git log --branches -1 --pretty=format:"%H") && cd ..
          cd ios && git fetch && git checkout $(git log --branches -1 --pretty=format:"%H") && cd ..
          cd ntp && git fetch && git checkout $(git log --branches -1 --pretty=format:"%H") && cd ..

      - name: Push to GitHub
        run: |
          git config --global user.name dothq-robot
          git config --global user.email 72629236+dothq-robot@users.noreply.github.com
          git status
          git add desktop android ios ntp
          git commit -m "👽 Update submodules"
          git push origin main