name: Update submodules

on:
  schedule:
    - cron: '*/1 * * * *' # every minute
  workflow_dispatch: # manually run
  
jobs:
  sync:

    runs-on: ubuntu-latest
    steps:
    - uses: snickerbockers/submodules-init@v4