name: Update submodules

on:
  schedule:
    - cron: '*/1 * * * *' # every minute
  workflow_dispatch: # manually run
  
jobs:
  upsm:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive