name: Update submodules

on:
  schedule:
    - cron: '*/1 * * * *' # every minute
  workflow_dispatch: # manually run
  
jobs:
  sync:

    runs-on: ubuntu-latest
    steps:
    - name: Update submodules
      run: git clone --recurse-submodules https://github.com/dothq/browser && cd browser && git submodule update --remote --recursive && git add . && git commit -m "👪 Pull in submodule changes" && git push origin main